### ISSUE TITLE
SCK rate

### ISSUE THREAD

**Issue by nazikus** [mk-fg/sht-sensor#6]
Hi, I've seen in readme that changing SCK rate is not implemented yet. But can you give me a clue how to achieve it with your app? I went through the source code of sht-sensor and couldn't figure it out. 
Thanks

**Comment by nazikus** [comment]
The reason I'm thinking of lowering SCK, because I have pretty long cable (about 20m) and I get an error "Command ACK failed on step-2". Maybe I should look elsewhere to solve this problem, any hints?

**Comment by mk-fg** [comment]
Hi,

There isn't much in the code that controls that rate, as it should be kinda slow anyway, with bit-banging done from python through sysfs gpio interface.

But to make it consistent and then set to something you want, best place to do it should be "_sck_tick" method here:
https://github.com/mk-fg/sht-sensor/blob/master/sht_sensor/sensor.py#L133-L135

It's used every time when clock must go 0->1 or 1->0, with example right below linked lines.

To set an upper limit on how fast clock can tick, you can simply put higher value into sleep() function there - I suspect sensor logic won't care even if it'd be seconds (as it doesn't have its own clock to know).

Or, to make it somewhat more consistent, I'd suggest to:

- Use monotonic clock - e.g. using python 2.7 code from here: https://github.com/mk-fg/python-pulse-control/blob/master/pulsectl/_pulsectl.py#L30-L42

    Python 3.x has this func as `time.monotonic()`, but 2.x only has `time.time()`, which should not be used for such purposes.

- On every call to "_sck_tick", get last tick and current (monotonic clock) timestamp, sleep until "last_ts + tick_interval" if it's still in the future, store current timestamp (either post-sleep or pre-sleep + delay) as "last_ts".

That way, you shouldn't have any extra delays when ticks are separated in time far enough already.

Though making a syscall to get monotonic timestamp through python ctypes interface with all the associated overhead might cause enough delay as it is, without any sleep :)
Don't really have any back-of-the-napkin numbers on that however, and these should depend heavily on cpu and system load anyway.

Might implement it here eventually, should be rather trivial, but need to find/hook-up sensor to something for testing, and need to attend to other stuff at the moment.

**Comment by mk-fg** [comment]
>Might implement it here eventually, should be rather trivial, but need to find/hook-up sensor to something for testing

Done.

More info on how to specify it here:
https://github.com/mk-fg/sht-sensor/#max-bit-banging-frequency-control

Datasheet indeed says that min frequency is 0, i.e. "take as long as you want" ;)
Testing with Beaglebone Black though, values as low as 20Hz (50ms delay between changes) work reliably, but 10Hz doesn't... wonder why.
Fairly sure you want higher values anyway.

Let me know if it works for you, or maybe has any issues.

**Comment by nazikus** [comment]
wow, thanks for quick update! appreciate it

Although, in my case, it seems its not the long cable issue. I have tried with short cable again (~5cm) and I still get "Command ACK failed on step-2". Can you please describe possible reasons for this error?

I tried several variations connecting the sensor, with different GPIO pins, 3.3V and 5V, and also tried sht1x lib you reference in readme. The same problem. I've tested with oscilloscope and SCK signal is quite strong, but DAT is silent. I assume I could screw up my sensor while soldering back'n'forth to different wires, since [SHT75](http://www.raphnet.net/electronique/usbtenki/sht75.jpg) is quite gentle (comparing to [SHT25](https://www.embeddedadventures.com/images/uploaded_images/MOD-1018_6_600.jpg), for example). So I just ordered new one just to make sure, waiting for it to arrive.

I will try updated frequency control for sure, I'll post an comment here when new sensor arrives. thanks

**Comment by mk-fg** [comment]
> still get "Command ACK failed on step-2". Can you please describe possible reasons for this error?

After sending preamble and command the the sensor, DATA line goes into IN mode and following sequence should be observed:

- SCK=0 (after last bit of command)
- SCK=1
- DATA=1 ("ACK step 1" from sensor)
- SCK=0
- DATA=0 ("ACK step 2" from sensor)

That way sensor should acknowledge that it has received the command, according to the datasheet.

Reading e.g. temperature then is done by sending "get temperature" command (with that ACK sequence checked at the end), followed by reading value + value + crc bits from sensor, each separated by similar ACK sequence sent to the sensor (indicating that we want second copy of value and crc)... iirc.

> tested with oscilloscope and SCK signal is quite strong, but DAT is silent

If you don't see signals from the board there, then maybe it's the connection after all?

Might also be sensor pulling the value up/down too strongly, I guess, so that setting 1/0 on that kind of short-circuited pin doesn't make a difference, but that seem unlikely, and probably easy to rule-out by disconnecting the sensor temporarily and listening for command bits there.

**Comment by mk-fg** [comment]
Hm, right, with sensor soldered to wires like that, guess it might be not as trivial to disconnect it as I made it sound above, except maybe cutting wires and re-soldering them later...

**Comment by mk-fg** [comment]
Also, as a side note, SHT75 legs fit well into (or rather go through) 1.27mm-step sockets, e.g.:
https://www.aliexpress.com/item/100-pcs-0-050-2x4-P-8-Pin-1-27-mm-Male-Female-SMT-Female-DIP/32769141515.html
And these should be always safe to solder without risking any damage to the (unplugged) sensor.
